---
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  prometheus:
    enabled: true
    tls:
      enabled: true
      server:
        existingSecret: cilium-operator-metrics-tls
        mtls:
          enabled: true

hubble:
  metrics:
    enableOpenMetrics: true
    tls:
      enabled: true
      server:
        existingSecret: hubble-metrics-tls
        mtls:
          enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true

envoy:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
