apiVersion: v1
kind: Secret
metadata:
  name: falco-user
  namespace: logging
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "falco"
type: kubernetes.io/basic-auth
stringData:
  username: falco
  password: "MySeCreTValu3"
  roles: falco_writer_role
