apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: falco-client-cert
  namespace: falco
spec:
  secretName: falco-client-cert
  commonName: falco-client
  issuerRef:
    name: our-own-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
    rotationPolicy: Always
  usages:
  - client auth
