---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-s3-config
  namespace: monitoring
type: Opaque
stringData:
  objectstorage.yaml: |
    type: S3
    config:
      bucket: our-amazing-s3-bucket-store
      endpoint: s3.us-east-1.amazonaws.com
      access_key: WELOVEPIZZA
      secret_key: THISISVERYSECRETOKAY
