---

query:
  replicaCount: 2
  https:
    enabled: false
  grpc:
    server:
      tls:
        enabled: false
    client:
      tls:
        enabled: false

  extraFlags:
    - --http.config=/certs/http/http-tls.yaml
    - --grpc-server-tls-cert=/certs/server/tls.crt
    - --grpc-server-tls-key=/certs/server/tls.key
    - --grpc-server-tls-client-ca=/certs/server/ca.crt
    - --grpc-client-tls-secure
    - --grpc-client-tls-cert=/certs/client/tls.crt
    - --grpc-client-tls-key=/certs/client/tls.key
    - --grpc-client-tls-ca=/certs/client/ca.crt
    - --grpc-client-server-name=prometheus-kube-prometheus-thanos-discovery.monitoring.svc.cluster.local

  extraVolumes:
    - name: thanos-query-server-tls
      secret:
        secretName: thanos-query-tls
    - name: thanos-query-client-tls
      secret:
        secretName: monitoring-client-tls
    - name: thanos-query-http-tls-config
      configMap:
        name: thanos-query-http-tls-config

  extraVolumeMounts:
    - name: thanos-query-server-tls
      mountPath: /certs/server
      readOnly: true
    - name: thanos-query-client-tls
      mountPath: /certs/client
      readOnly: true
    - name: thanos-query-http-tls-config
      mountPath: /certs/http
      readOnly: true

  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  customLivenessProbe:
    httpGet:
      path: /-/healthy
      port: 10902
      scheme: HTTPS
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 6
  customReadinessProbe:
    httpGet:
      path: /-/ready
      port: 10902
      scheme: HTTPS
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 6

storegateway:
  replicaCount: 2
  https:
    enabled: true
    existingSecret: thanos-storegateway-tls
    certFilename: tls.crt
    keyFilename: tls.key
    caFilename: ca.crt
    clientAuthType: RequireAndVerifyClientCert

  grpc:
    server:
      tls:
        enabled: false
    client:
      tls:
        enabled: false

  extraFlags:
    - --grpc-server-tls-cert=/certs/server/tls.crt
    - --grpc-server-tls-key=/certs/server/tls.key
    - --grpc-server-tls-client-ca=/certs/server/ca.crt

  extraVolumes:
    - name: thanos-storegateway-server-tls
      secret:
        secretName: thanos-storegateway-tls

  extraVolumeMounts:
    - name: thanos-storegateway-server-tls
      mountPath: /certs/server
      readOnly: true

compactor:
  replicas: 1
  https:
    enabled: true
    existingSecret: thanos-compactor-tls
    certFilename: tls.crt
    keyFilename: tls.key
    caFilename: ca.crt
    clientAuthType: RequireAndVerifyClientCert
