apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kibana-access
  namespace: logging
spec:
  endpointSelector:
    matchLabels:
      k8s:common.k8s.elastic.co/type: kibana
      k8s:kibana.k8s.elastic.co/name: quickstart
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: logging
    toPorts:
    - ports:
      - port: "5601"
        protocol: TCP
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: elastic-system
        k8s:app.kubernetes.io/name: elastic-operator
    toPorts:
    - ports:
      - port: "5601"
        protocol: TCP
  - fromEntities:
    - ingress
    toPorts:
    - ports:
      - port: "5601"
        protocol: TCP
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: logging
        k8s:common.k8s.elastic.co/type: elasticsearch
        k8s:elasticsearch.k8s.elastic.co/cluster-name: quickstart
    toPorts:
    - ports:
      - port: "9200"
        protocol: TCP
  - toEntities:
    - kube-apiserver
    - host
    toPorts:
    - ports:
      - port: "6443"
        protocol: TCP