---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-nginx-tls
  namespace: monitoring
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stderr warn;
    pid /tmp/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      server {
        listen 3001 ssl;
        ssl_certificate     /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        ssl_client_certificate /etc/nginx/certs/ca.crt;
        ssl_verify_client optional;

        location / {
          proxy_pass http://localhost:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-internal
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
    grafana-endpoint: internal-https
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
    - name: https-internal
      port: 3001
      targetPort: 3001
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-grafana
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      port: https-internal
      scheme: https
      scrapeTimeout: 30s
      tlsConfig:
        ca:
          secret:
            key: ca.crt
            name: monitoring-client-tls
        cert:
          secret:
            key: tls.crt
            name: monitoring-client-tls
        insecureSkipVerify: false
        keySecret:
          key: tls.key
          name: monitoring-client-tls
        serverName: prometheus-grafana.monitoring.svc.cluster.local
  jobLabel: prometheus
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      grafana-endpoint: internal-https
