apiVersion: v1
kind: ConfigMap
metadata:
  name: es-role-mapping
  namespace: logging
data:
  role_mapping.yml: |
    superuser:  # For admin access (use sparingly)
      - "CN=logstash-client"
      - "CN=kibana-client"
    kibana_admin:  # For Kibana
      - "CN=kibana-client"
    beats_admin:  # For Filebeat/Metricbeat ingestion
      - "CN=filebeat-client"
      - "CN=metricbeat-client"
    logstash_internal:  # For Logstash
      - "CN=logstash-client"
