apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart-logstash
  namespace: logging
spec:
  version: 9.3.1
  count: 1
  elasticsearchRefs:
  - name: quickstart
    clusterName: es
  services:
    - name: beats
      service:
        spec:
          type: ClusterIP
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044
  podTemplate:
    spec:
      containers:
      - name: logstash
        resources:
          limits:
            cpu: 1
            memory: 2Gi
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        volumeMounts:
        - name: server-cert
          mountPath: /usr/share/logstash/config/server.crt
          subPath: tls.crt
        - name: server-cert
          mountPath: /usr/share/logstash/config/server.key
          subPath: tls.key
        - name: client-cert
          mountPath: /usr/share/logstash/config/client.crt
          subPath: tls.crt
        - name: client-cert
          mountPath: /usr/share/logstash/config/client.key
          subPath: tls.key
        - name: our-own-ca
          mountPath: /usr/share/logstash/config/ca.crt
          subPath: ca.crt
      volumes:
      - name: server-cert
        secret:
          secretName: logstash-server-cert
      - name: client-cert
        secret:
          secretName: logstash-client-cert
      - name: our-own-ca
        secret:
          secretName: our-own-ca
  pipelines:
  - pipeline.id: main
    config.string: |
      input {
        beats {
          port => 5044
          ssl_enabled => true
          ssl_certificate_authorities => ["/usr/share/logstash/config/ca.crt"]
          ssl_certificate => "/usr/share/logstash/config/server.crt"
          ssl_key => "/usr/share/logstash/config/server.key"
          ssl_client_authentication => "required"
        }
      }
      filter {
        # Example grok for kubelet logs (adapt patterns)
        if [source] =~ "kubelet" {
          grok {
            match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:hostname} kubelet$$   [0-9]+   $$: %{GREEDYDATA:log_message}" }
          }
          date {
            match => [ "timestamp", "MMM dd HH:mm:ss" ]
          }
        }
      }
      output {
        elasticsearch {
          hosts => [ "${ES_ES_HOSTS}" ]
          user => "${ES_ES_USER}"
          password => "${ES_ES_PASSWORD}"
          ssl_certificate_authorities => ["/usr/share/logstash/config/ca.crt"]
          ssl_certificate => "/usr/share/logstash/config/client.crt"
          ssl_key => "/usr/share/logstash/config/client.key"
          index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        }
      }
