apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: logstash-client-cert
  namespace: logging
spec:
  secretName: logstash-client-cert
  commonName: logstash-client
  issuerRef:
    name: our-own-issuer
    kind: ClusterIssuer
  usages:
  - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
    rotationPolicy: Always
